### ISSUE TITLE
Timeline Scope

### ISSUE THREAD

**Issue by bergos** [rdfjs/shacl-ui#6]
For some technical issues, it's obvious that they are part of this Task Force, but for some, it's not. That requires finishing the scope. I would propose to set the deadline to 30th of June. On the 16th of June, we check if bigger issues are open and decide whether we need to meet in the week of the 19th of June.

Please leave a :+1: if you agree with this.

**Comment by tfrancart** [comment]
I just want to make sure that query components are within scope, not only viewing and editing.

**Comment by bergos** [comment]
It has been discussed in the 2023-06-23 meeting. This issue will be closed as there has been no further discussion, and the deadline has passed.
