### ISSUE TITLE
Subgroups

### ISSUE THREAD

**Issue by bergos** [rdfjs/shacl-ui#7]
I proposed two subgroups in the Kick Off Call:

## Ontology
Enhance the SHACL ontology for UI use cases.

## Component Interfaces
Define interfaces for reusable UI components.

Is this definition OK? Anything more specific to mention in the description? If you agree, please leave a :+1:. I will add the groups later to the README.

**Comment by tpluscode** [comment]
Off the top of my head, I'm thinking that maybe we could also do with a high-level group which would focus on use cases in a way that the others and feeds them requirements. Also, that would be a group to provide real-world scenarios, building upon the specs and using them to achieve practical goals (compare with "How-Tos" or "Tutorials" as described in #3)

**Comment by bergos** [comment]
We will stay with the two subgroups, as discussed in the 2023-06-23 meeting. The ontology subgroup will also cover topics like how-tos and tutorials.
