### ISSUE TITLE
Participation

### ISSUE THREAD

**Issue by bergos** [rdfjs/shacl-ui#8]
For the processes in how we work, it would be good to know how many people are willing to participate and how much time they can contribute on average per week. Please leave a comment with the number of hours and which part is of interest to you (ontology, component interfaces).

**Comment by bergos** [comment]
4h (ontology, component interfaces)

**Comment by danielbeeke** [comment]
4h (ontology, component interfaces)

**Comment by chasm** [comment]
2h (not sure yet)

**Comment by HolgerKnublauch** [comment]
2h (let's see where I can help)

**Comment by tpluscode** [comment]
4h (ontology, component interfaces)

@HolgerKnublauch your experience in having built DASH will be invaluable. Possibly in both areas

**Comment by ashleysommer** [comment]
2h. I'm mainly interested in exploring how I can integrate SHACL-UI into PySHACL, and what features that will open up to Users (form generation, auto formatting, etc).

**Comment by edmondchuc** [comment]
2h (ontology, component interfaces)

**Comment by bergos** [comment]
Based on the available time, we decided in the 2023-06-23 meeting to have biweekly meetings.
